"""added new columns in user for invite

Revision ID: 061174b6577f
Revises: 9c4d5b166433
Create Date: 2026-04-30 09:22:52.480358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061174b6577f'
down_revision: Union[str, Sequence[str], None] = '9c4d5b166433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('invite_token_expiry', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('is_invited', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_users_invite_token'), 'users', ['invite_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_invite_token'), table_name='users')
    op.drop_column('users', 'is_invited')
    op.drop_column('users', 'invite_token_expiry')
    op.drop_column('users', 'invite_token')
    # ### end Alembic commands ###
