"""drop email from clients

Revision ID: 15d1ac839417
Revises: 201620f6121f
Create Date: 2026-05-21 22:55:33.018846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d1ac839417'
down_revision: Union[str, Sequence[str], None] = '201620f6121f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_clients_email'), 'clients', type_='unique')
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_clients_email'), 'clients', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
