"""add drive_folder_id to sites

Revision ID: 19a294c05029
Revises: 061174b6577f
Create Date: 2026-05-04 22:08:57.722224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a294c05029'
down_revision: Union[str, Sequence[str], None] = '061174b6577f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('drive_folder_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'drive_folder_id')
    # ### end Alembic commands ###
