"""add email to clients and client_id to users

Revision ID: 201620f6121f
Revises: cd51eb53cc38
Create Date: 2026-05-21 22:29:20.357850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201620f6121f'
down_revision: Union[str, Sequence[str], None] = 'cd51eb53cc38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_clients_email', 'clients', ['email'])
    op.add_column('users', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_users_client_id', 'users', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_client_id', 'users', type_='foreignkey')
    op.drop_column('users', 'client_id')
    op.drop_constraint('uq_clients_email', 'clients', type_='unique')
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###
