"""add work_entry_item_id to work_entry_photo

Revision ID: 5b959bec7163
Revises: 19a294c05029
Create Date: 2026-05-05 17:05:42.181625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b959bec7163'
down_revision: Union[str, Sequence[str], None] = '19a294c05029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('work_entry_photos_work_entry_id_fkey'), 'work_entry_photos', type_='foreignkey')
    op.create_foreign_key(None, 'work_entry_photos', 'work_entry_items', ['work_entry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_entry_photos', type_='foreignkey')
    op.create_foreign_key(op.f('work_entry_photos_work_entry_id_fkey'), 'work_entry_photos', 'work_entries', ['work_entry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
